export const ENTITY_IMAGES = {
  'O Afogado':           '/img/Entidades/O%20Afogado.png',
  'O Rei das Montanhas':   '/img/Entidades/O%20Rei%20das%20Montanhas.png',
  'A Dama de Vermelho':  '/img/Entidades/A%20Dama%20de%20Vermelho.png',
  'O Andarilho':         '/img/Entidades/O%20Andarilho.png',
  'O Trovador':          '/img/Entidades/O%20Trovador.png',
  'O Primeiro Amanhecer':'/img/Entidades/O%20Primeiro%20Amanhecer.png',
  'O Senhor do Silêncio':  '/img/Entidades/O%20Senhor%20do%20Sil%C3%AAncio.png',
  'O Arquiteto Sem Face':'/img/Entidades/O%20Arquiteto%20Sem%20Face.png',
  'O Guardião do Tempo': '/img/Entidades/O%20Guardi%C3%A3o%20do%20Tempo.png',
  'A Tecelã':            '/img/Entidades/A%20Tecel%C3%A3.png',
  'O Espelho Dourado':   '/img/Entidades/O%20Espelho%20Dourado.png',
  'A Dama dos Desejos':  '/img/Entidades/A%20Dama%20dos%20Desejos.png',
  'O Mestre do Banquete':'/img/Entidades/O%20Mestre%20do%20Banquete.png',
  'O Ruivo':             '/img/Entidades/O%20Ruivo.png',
  'O Sonolento':         '/img/Entidades/O%20Sonolento.png',
  'O Mil Olhos':           '/img/Entidades/O%20Mil%20Olhos.png',
  'O Colecionador':      '/img/Entidades/O%20Colecionador.png',
}

export const ENTITY_DOMAIN_IMAGES = {
  'O Afogado':           '/img/Dominio/O%20Afogado.png',
  'O Rei das Montanhas':   '/img/Dominio/O%20Rei%20das%20Montanhas.png',
  'A Dama de Vermelho':  '/img/Dominio/A%20Dama%20de%20Vermelho.png',
  'O Andarilho':         '/img/Dominio/O%20Andarilho.png',
  'O Trovador':          '/img/Dominio/O%20Trovador.png',
  'O Primeiro Amanhecer':'/img/Dominio/O%20Primeiro%20Amanhecer.png',
  'O Senhor do Silêncio':  '/img/Dominio/O%20Senhor%20dos%20Sil%C3%AAncio.png',
  'O Arquiteto Sem Face':'/img/Dominio/O%20Arquiteto%20Sem%20Face.png',
  'O Guardião do Tempo': '/img/Dominio/O%20Guardi%C3%A3o%20do%20Tempo.png',
  'A Tecelã':            '/img/Dominio/A%20Tecel%C3%A3.png',
  'O Espelho Dourado':   '/img/Dominio/O%20Espelho%20Dourado.png',
  'A Dama dos Desejos':  '/img/Dominio/A%20Dama%20dos%20Desejos.png',
  'O Mestre do Banquete':'/img/Dominio/O%20Mestre%20do%20Banquete.png',
  'O Ruivo':             '/img/Dominio/O%20Ruivo.png',
  'O Sonolento':         '/img/Dominio/O%20Sonolento.png',
  'O Mil Olhos':           '/img/Dominio/O%20Mil%20Olhos.png',
  'O Colecionador':      '/img/Dominio/O%20Colecionador.png',
}

export const ENTITY_LORE = {
  'O Afogado': {
    personalidade: 'Paciente e inevitável, O Afogado raramente age de forma impulsiva. Ele observa em silêncio, como algo escondido sob a superfície esperando o momento certo para puxar alguém para baixo. Sua crueldade não está na violência repentina, mas no desgaste lento: culpa, medo, arrependimento e desespero. Velhas histórias dizem que ele oferece falsas esperanças antes de consumir suas vítimas, permitindo que elas acreditem que escaparão até o último instante.',
    descricao: 'O Afogado não representa apenas o oceano, mas toda água profunda o bastante para esconder algo. Mares, rios escuros, lagos silenciosos, cavernas inundadas e regiões cobertas por neblina carregam sua presença. Dizem que ele habita qualquer lugar onde algo tenha sido perdido e jamais encontrado novamente. Para muitos povos costeiros, a água não é apenas um elemento natural, mas uma porta para aquilo que o mundo tenta esquecer.\n\nAlguns afirmam ter visto um velho capitão envolto por correntes e mantos encharcados caminhando sobre águas rasas. Outros descrevem apenas olhos azulados observando nas profundezas. Há relatos onde ele surge como uma figura encapuzada parada na margem durante tempestades, enquanto em outras histórias ele jamais é visto diretamente — apenas sentido pela névoa fria e pelo som distante de correntes arrastando sob a água.\n\nMarinheiros acreditam que O Afogado caça aqueles consumidos pela culpa ou arrogância. Existe uma crença antiga de que toda água profunda pertence parcialmente a ele. E que, quando alguém desaparece sem deixar rastros, talvez não tenha morrido. Talvez apenas tenha sido levado para o fundo.',
    dominio: {
      nome: 'O Mar Sem Horizonte',
      desc: 'O domínio do Afogado é um oceano infinito mergulhado em uma noite eterna. O céu permanece limpo, tomado por incontáveis estrelas refletidas sobre águas absurdamente calmas, criando a sensação de que o mar e o firmamento se misturam em um único vazio silencioso.\n\nNo centro desse oceano navega um antigo navio de madeira escurecida pelo tempo. Não existem tripulantes. Nenhum som de passos. Nenhuma vela tremula ao vento, porque naquele lugar não existe vento algum. Ainda assim, a embarcação continua navegando lentamente sobre as águas imóveis.\n\nA única coisa que quebra o silêncio são as almas. Sob o casco do navio, incontáveis silhuetas afundadas deslizam lentamente pelas profundezas escuras como corpos carregados pela correnteza. Algumas observam os visitantes enquanto passam. Outras parecem apenas continuar descendo eternamente rumo ao fundo invisível do mar.\n\nDizem que o Afogado não navega pelo oceano comum. Ele navega pelo mar da vida. Cada alma perdida, memória esquecida ou destino abandonado eventualmente cruza aquelas águas.\n\nAo entrar nesse domínio, o visitante normalmente encontra o Afogado parado no convés observando o horizonte escuro ou segurando silenciosamente o leme da embarcação. Ele raramente fala. Quando fala, sua voz parece distante, abafada e pesada como algo vindo do fundo do oceano.\n\nO ambiente é tomado por uma quantidade absurda de mana. A energia mágica parece fluir pelo ar como água invisível, tornando feitiços mais vivos, intensos e perigosamente fáceis de conjurar. Muitos magos descrevem a sensação de estar naquele lugar como mergulhar a mente em um oceano mágico profundo demais para ser compreendido completamente.\n\nMas permanecer ali por tempo demais é perigoso. O silêncio constante, o balanço suave do navio e as vozes distantes sob a água lentamente fazem pensamentos afundarem. Alguns visitantes começam a esquecer memórias importantes. Outros sentem uma vontade crescente de apenas parar… e se deixar cair no mar escuro. Porque o domínio do Afogado não tenta matar seus visitantes. Ele tenta fazê-los pertencer àquelas águas.',
    },
    graca: {
      nome: 'Maré Arcana',
      desc: 'Recupera 1d4 PM no início de cada turno enquanto estiver em combate ativo. Além disso, o ganho adicional de mana durante descansos aumenta o valor da recuperação padrão mais bônus o valor da Presença.',
    },
    requisito: 'Ao menos 3 magias do elemento Água (iniciais aprimoradas ao nível Elite ou superior; Antigas ao nível Maior ou superior). Possuir perícia Tenacidade ou Vontade em nível Básico (+2).',
    frase: '"O Capitão sempre recebe antes da viagem começar."',
  },

  'O Rei das Montanhas': {
    personalidade: 'Antigo além da compreensão mortal, o Rei das Montanhas é severo, imóvel e impossível de apressar. Ele não sente compaixão nem crueldade; apenas existe como algo eterno observando civilizações nascerem e desaparecerem. Tudo muda, tudo morre, tudo é esquecido — menos ele. Algumas lendas afirmam que jamais pronuncia palavras, pois não existe necessidade para alguém que já viu incontáveis eras passarem.',
    descricao: 'O Rei das Montanhas representa a permanência absoluta. Não apenas a pedra e as montanhas, mas tudo aquilo que permanece mesmo após eras incontáveis. Ruínas esquecidas, cidades soterradas, trilhas apagadas pelo tempo existem sob seu domínio silencioso. Para muitos povos antigos, as montanhas não nasceram naturalmente — seriam partes adormecidas de seu corpo colossal emergindo do mundo.\n\nExistem incontáveis altares erguidos em cavernas representando sua imagem: um gigante colossal sentado sobre um trono de pedra, tão grandes que preenchem salões subterrâneos inteiros. Em certas ruínas, muitas dessas imagens não parecem ter sido esculpidas, mas descobertas já prontas dentro da própria rocha.\n\nSua aparência é a de um gigante ancestral formado por rochas rachadas, minerais luminosos e pedra escurecida pelo tempo. Partes de seu corpo lembram ruínas fossilizadas, como se cidades inteiras tivessem sido engolidas e incorporadas à sua estrutura ao longo das eras.',
    dominio: {
      nome: 'O Trono Sob a Montanha',
      desc: 'O domínio do Rei das Montanhas existe nas profundezas além do mundo conhecido, enterrado sob camadas incontáveis de pedra antiga e silêncio absoluto. Aqueles que atravessam os limites desse lugar frequentemente descrevem a sensação de estarem entrando não em uma construção… mas dentro da própria memória do mundo.\n\nO salão é colossal. Tão vasto que sua extensão desaparece na escuridão acima, onde o teto não pode ser completamente visto. Gigantescas estátuas de pedra se erguem dos dois lados, alinhadas como antigos soberanos esquecidos observando eternamente os visitantes. Algumas seguram armas monumentais. Outras apenas permanecem sentadas em silêncio com as mãos apoiadas sobre os joelhos. Todas parecem antigas demais para terem sido esculpidas por mãos mortais.\n\nEnormes colunas sustentam o salão, cobertas por inscrições na antiga língua dos Gigantes — marcas profundas entalhadas diretamente na rocha como decretos destinados a sobreviver ao fim das eras. Entre elas pendem bandeiras desgastadas de reinos desaparecidos há milênios, preservadas de maneira impossível apesar do tempo.\n\nNo final do salão repousa o trono. Uma estrutura gigantesca talhada em pedra negra e minerais verde-esmeralda, tão grande que parece feita para uma montanha sentar-se sobre ela. E sentado ali permanece o Rei das Montanhas. Imóvel. Silencioso. Observando.\n\nSeu corpo colossal parece parcialmente fundido ao próprio trono, como se ambos fossem parte da mesma estrutura ancestral. Seus olhos brilham em verde-esmeralda profundo dentro da escuridão, lembrando cristais antigos enterrados sob o mundo.\n\nQuando fala, sua voz ecoa pelo salão inteiro como pedras deslizando lentamente umas sobre as outras. Pesada. Antiga. Calmamente esmagadora.\n\nNaquele domínio, o tempo parece desacelerar. Sons tornam-se distantes, pensamentos ficam pesados e até magia assume uma presença mais sólida e densa. Muitos visitantes relatam sentir o peso da própria existência pressionando seus corpos enquanto permanecem diante do Rei. Porque naquele lugar tudo parece pequeno. Inclusive deuses menores.',
    },
    graca: {
      nome: 'Coroa do Rei',
      desc: 'Manifesta uma coroa de pedra invisível para todos exceto seu portador. Concede +2 de Defesa e Barreira Arcana: absorve +10 de dano mágico uma vez por combate.',
    },
    requisito: 'Ao menos 3 magias do elemento Terra (iniciais aprimoradas ao nível Elite ou superior; Antigas ao nível Maior ou superior). Possuir Vitalidade pelo menos +2.',
    frase: '"O Rei coroa apenas aquele que já provou suportar o peso do mundo."',
  },

  'A Dama de Vermelho': {
    personalidade: 'Impulsiva, intensa e absolutamente sincera, a Dama de Vermelho despreza tudo aquilo que permanece imóvel por tempo demais. Ela vê estagnação como uma forma lenta de morte. Suas emoções são violentas e transparentes, mudando como as próprias chamas. Pode demonstrar calor e fascínio em um instante, apenas para se tornar devastadora no momento seguinte. Seus seguidores acreditam que ela jamais mente, porque o fogo nunca esconde sua verdadeira natureza.',
    descricao: 'A Dama de Vermelho não representa apenas incêndios ou destruição, mas a natureza inevitável da transformação. O fogo que aquece também consome, a chama que ilumina também reduz tudo a cinzas. Ela existe em vulcões, fogueiras, cidades queimando, paixões intensas e desejos impossíveis de controlar.\n\nEla normalmente assume a forma de uma mulher extremamente bela, quase impossível de ser ignorada. Sua pele é branca como porcelana iluminada pelo brilho de brasas, criando um contraste intenso com seus longos cabelos vermelhos que se movem como fogo vivo. Ela veste um longo vestido vermelho formado por tecidos finos misturados a chamas vivas que nunca se apagam.\n\nSeus seguidores acreditam que as chamas libertam o mundo de sua podridão. Para eles, destruir não significa acabar com algo, mas abrir espaço para que outra coisa nasça.',
    dominio: {
      nome: 'O Jardim das Cinzas',
      desc: 'O domínio da Dama de Vermelho existe no coração de um mundo consumido eternamente pelas chamas. Não há céu verdadeiro naquele lugar — apenas nuvens escuras cortadas pelo brilho constante de incêndios distantes e rios de magma atravessando o horizonte como veias abertas dentro da terra.\n\nNo centro desse inferno ergue-se um castelo colossal de pedra negra rachada pelo calor, envolto por chamas que jamais se apagam. Torres incandescentes iluminam o vazio ao redor enquanto cinzas caem lentamente como neve ardente sobre os jardins externos. Mesmo os jardins queimam. Árvores carbonizadas continuam vivas apesar do fogo eterno consumindo seus galhos. Flores vermelhas surgem entre brasas vivas, abrindo e fechando lentamente como se respirassem calor. Estátuas derretidas deformam-se lentamente pelo calor absurdo daquele lugar, como memórias incapazes de permanecer intactas diante da presença da Dama.\n\nEla costuma caminhar sozinha entre os jardins em chamas, seus pés atravessando brasas sem deixar marcas enquanto observa silenciosamente o fogo consumir tudo ao redor. O ambiente inteiro lembra o interior de um vulcão vivo.\n\nO calor é quase insuportável para criaturas mortais. Respirar se torna difícil, suor evapora antes mesmo de cair e cada instante naquele domínio parece pressionar corpo e mente contra um limite impossível de suportar por muito tempo. Mas existe algo perigosamente belo naquele lugar. As chamas dançam como seda viva. As cinzas brilham como estrelas apagadas. E no centro da destruição, a Dama de Vermelho parece mais viva do que qualquer outra coisa existente.\n\nMuitos visitantes descrevem uma sensação estranha ao permanecer naquele domínio: o desejo crescente de deixar tudo para trás e simplesmente permitir que o fogo consuma aquilo que ainda dói dentro deles. Porque naquele lugar, destruir e libertar parecem a mesma coisa.',
    },
    graca: {
      nome: 'Manto Vermelho',
      desc: 'Usando uma Ação Livre, um manto de fogo surge ao redor do conjurador durante 5 rodadas. O usuário torna-se Imune a Dano de Fogo. Criaturas adjacentes recebem 1d8 de dano de fogo no início de cada turno (salvaguarda de Reflexo = metade). Utilizável uma vez por Descanso Longo.',
    },
    requisito: 'Ao menos 3 magias do elemento Fogo (iniciais aprimoradas ao nível Elite ou superior; Antigas ao nível Maior ou superior). Possuir Presença pelo menos +2.',
    frase: '"Tudo que arde intensamente deixa cinzas para trás."',
  },

  'O Andarilho': {
    personalidade: 'O Andarilho é inquieto, curioso e impossível de compreender completamente. Pode surgir como uma presença gentil guiando viajantes perdidos, mas também pode trazer destruição repentina como ventos violentos. Ele raramente demonstra malícia direta. Em algumas histórias ajuda pessoas sem motivo aparente. Em outras, conduz homens para caminhos sem volta apenas porque desejava ver até onde chegariam. O Andarilho odeia aprisionamento.',
    descricao: 'O Andarilho representa aquilo que jamais permanece no mesmo lugar. Ele existe nos ventos frios antes de tempestades, nas estradas esquecidas, nas folhas carregadas pelo ar e nos caminhos que surgem sem explicação diante de viajantes perdidos.\n\nEle raramente possui uma única forma fixa. Em muitas histórias surge como um jovem de aparência livre, usando roupas simples e gastas pelo tempo que se movem mesmo quando não existe vento. Outros relatos descrevem um velho andarilho de cabelos longos caminhando por estradas vazias. Também existem histórias sobre uma mulher extremamente bela surgindo entre neblinas, seus cabelos dançando como fumaça ao vento.\n\nIndependentemente da forma, existe algo em comum em todos os relatos: O Andarilho jamais permanece por muito tempo. Ele surge como o vento. E desaparece da mesma forma.',
    dominio: {
      nome: 'A Encruzilhada Sem Fim',
      desc: 'O domínio do Andarilho é uma estrada infinita perdida entre realidades que nunca permanecem iguais por muito tempo. Não existe começo ou destino visível naquele lugar, apenas caminhos de terra se dividindo constantemente em novas direções enquanto o horizonte muda sem parar.\n\nNo centro do domínio existe uma grande encruzilhada. É ali que o Andarilho costuma esperar. Às vezes surge como um jovem sorridente apoiado em uma velha placa de estrada. Outras vezes como um ancião silencioso observando o horizonte com um cajado nas mãos. Em certos momentos aparece como uma mulher envolta por névoa caminhando lentamente entre os caminhos. E enquanto fala…Sua aparência muda. Vozes se misturam. Rostos trocam lentamente. Idades mudam entre uma frase e outra. Como se nenhuma forma fosse capaz de contê-lo completamente.\n\nCada estrada da encruzilhada leva para paisagens diferentes. Algumas atravessam desertos dourados sob sóis gigantescos. Outras entram em florestas impossíveis onde o céu muda de cor constantemente. Certos caminhos parecem conduzir para cidades desconhecidas, mares suspensos no vazio ou ruínas que desaparecem quando observadas diretamente.\n\nMas nada permanece estável. Montanhas mudam de lugar. Placas apontam para direções diferentes. Noite e dia alternam em poucos instantes. Estradas surgem onde antes havia vazio. Até pensamentos parecem mais difíceis de manter intactos naquele domínio.\n\nO próprio Andarilho raramente oferece respostas diretas. Em vez disso, faz perguntas, conta histórias incompletas ou aponta silenciosamente para caminhos que o visitante não havia percebido antes. Muitos acreditam que cada estrada representa escolhas possíveis, destinos abandonados ou vidas que poderiam ter existido.\n\nE talvez o mais assustador seja que algumas dessas estradas parecem levar diretamente de volta para memórias esquecidas do próprio visitante.',
    },
    graca: {
      nome: 'Viajante',
      desc: 'O pactuado recebe permanentemente +3 metros de Movimento. Uma vez a cada descanso, durante combate, o usuário pode escolher receber: um Movimento adicional ou uma Reação adicional. Além disso, ignora terreno difícil natural.',
    },
    requisito: 'Ao menos 3 magias do elemento Vento (iniciais aprimoradas ao nível Elite ou superior; Antigas ao nível Maior ou superior). Possuir Destreza pelo menos +2.',
    frase: '"Nenhum viajante corre eternamente sem que a estrada cobre descanso."',
  },

  'O Trovador': {
    personalidade: 'O Trovador é intenso, energético e impossível de ignorar. Possui um carisma quase sobrenatural, atraindo olhares e emoções com facilidade, mas existe algo perigoso por trás de sua beleza. Assim como uma tempestade pode começar bela antes de se tornar devastadora, O Trovador alterna entre fascínio e destruição sem aviso. Seus seguidores acreditam que vidas comuns são desperdícios silenciosos, e que existir significa deixar marcas tão fortes quanto trovões rasgando o céu.',
    descricao: 'O Trovador representa o som da destruição antes dela acontecer. Ele existe no estrondo distante das tempestades, no brilho violento dos relâmpagos e na energia selvagem que antecede o caos. Seu domínio não está apenas nos raios, mas na sensação de tensão que toma o ar segundos antes da tempestade cair sobre o mundo.\n\nEle normalmente assume a forma de um homem extremamente belo e jovem, com aparência elegante e presença impossível de ignorar. Seus cabelos longos se movem como fumaça tempestuosa atravessada por pequenos clarões elétricos. Seus olhos são azul-claro quase cinza, brilhando como relâmpagos presos atrás das pupilas. Suas roupas lembram mantos escuros feitos de nuvens carregadas com detalhes luminosos semelhantes a veios de eletricidade.\n\nExiste uma antiga superstição: "Quando o céu canta, O Trovador está próximo." E quando ele está próximo, a tempestade sempre vem.',
    dominio: {
      nome: 'O Grande Teatro da Tempestade',
      desc: 'O domínio do Trovador se manifesta como um teatro colossal perdido em meio a uma tempestade eterna. Do lado de fora, relâmpagos atravessam o céu incessantemente enquanto chuva e vento parecem se mover no ritmo de uma música invisível. Entretanto, ao cruzar suas enormes portas douradas, todo som externo desaparece instantaneamente.\n\nLá dentro existe apenas o espetáculo. O teatro é grandioso, iluminado por lustres azulados que brilham como eletricidade viva suspensa acima do vazio. Fileiras intermináveis de cadeiras antigas cercam um enorme palco central envolto por cortinas escuras semelhantes a nuvens de tempestade.\n\nTodos que entram naquele domínio inevitavelmente acabam sentados nos camarotes superiores. Assistindo. Sempre assistindo. No palco, uma peça ocorre constantemente.\n\nA história muda conforme os visitantes presentes, assumindo formas diferentes para cada pessoa. Algumas encenações mostram guerras antigas. Outras representam tragédias futuras, lembranças esquecidas ou momentos importantes da vida daqueles que observam.\n\nOs atores raramente possuem rosto. Ainda assim, todos parecem familiares demais. Acima do palco, o Trovador conduz a apresentação como um maestro absoluto da tempestade. Sua voz ecoa pelo teatro inteiro enquanto narra cada cena com energia intensa e quase hipnótica. Atrás dele, uma gigantesca orquestra toca músicas violentas e emocionais capazes de fazer o próprio ambiente vibrar.\n\nNos momentos mais intensos da peça…Trovões explodem pelo salão. Relâmpagos cortam o teto do teatro como flashes divinos. Luzes iluminam o palco com violência quase sobrenatural. E o som da tempestade se mistura à música até se tornar impossível distinguir um do outro.\n\nPermanecer naquele domínio é emocionalmente sufocante. Cada cena parece atingir diretamente pensamentos, medos e emoções escondidas dentro dos espectadores. Alguns começam a chorar sem perceber. Outros sentem raiva, euforia ou desespero crescendo conforme a apresentação continua. Porque o Trovador não apenas conta histórias. Ele faz todos senti-las.',
    },
    graca: {
      nome: 'Silêncio Antes da Tempestade',
      desc: 'Uma vez a cada descanso, ativado como Ação Livre. Durante 1 rodada, todas as criaturas hostis ao redor ficam incapazes de utilizar Magias. Após esse efeito terminar, o pactuado recebe +10 na rolagem de seu primeiro ataque físico ou mágico realizado até o final do próximo turno.',
    },
    requisito: 'Ao menos 3 magias do elemento Trovão (iniciais aprimoradas ao nível Elite ou superior; Antigas ao nível Maior ou superior). Possuir perícia Carisma ou Enganação em nível Básico (+2).',
    frase: '"Após o trovão… até o mundo precisa de silêncio."',
  },

  'O Primeiro Amanhecer': {
    personalidade: 'Gentil, acolhedora e profundamente compassiva, O Primeiro Amanhecer transmite uma sensação de conforto impossível de explicar. Sua presença aquece não apenas o corpo, mas também a mente e o espírito. Entretanto, existe algo assustador por trás de sua compaixão. Quando decide preservar algo, torna-se absolutamente inflexível. Ela acredita que a existência deve continuar independentemente do custo.',
    descricao: 'O Primeiro Amanhecer representa o início de todas as coisas. Não apenas o nascer do sol, mas o primeiro respirar de uma vida, o despertar após a escuridão e a persistência da existência diante do fim. Muitos povos acreditam que toda luz no mundo é apenas um fragmento distante de seu brilho original.\n\nEla normalmente assume a forma de uma mulher de beleza sobrenatural, tão intensa que muitos têm dificuldade de olhar diretamente para ela. Seus longos cabelos dourados lembram os primeiros raios do sol atravessando o horizonte. Sua pele possui um brilho quente e delicado. Seus olhos carregam um brilho dourado intenso, profundo e acolhedor — mas também antigo e impossível de desafiar.\n\nExiste uma crença antiga: "Enquanto existir amanhecer, o mundo ainda não desistiu."',
    dominio: {
      nome: 'O Horizonte do Primeiro Sol',
      desc: 'O domínio do Primeiro Amanhecer existe em um penhasco silencioso acima de um oceano dourado imóvel. Não há noite naquele lugar. O sol permanece eternamente surgindo no horizonte, preso no exato instante do primeiro amanhecer da existência.\n\nO céu possui tons suaves de dourado, branco e laranja claro, como uma lembrança viva do primeiro dia do mundo. O ar é quente, leve e absurdamente silencioso. Não existe vento forte, tempestades ou ruídos intensos naquele domínio.\n\nApenas paz. No alto do penhasco existe um pequeno quiosque simples construído em madeira clara e detalhes dourados já desgastados pelo tempo. Dentro dele há uma mesa com duas cadeiras posicionadas lado a lado, ambas voltadas para o horizonte eterno.\n\nÉ ali que o Primeiro Amanhecer costuma permanecer. Sentada calmamente observando o nascer do sol que jamais termina.\n\nSua presença transmite conforto profundo, mas também algo esmagadoramente melancólico. Muitos visitantes sentem vontade de permanecer ali para sempre, apenas observando o horizonte ao lado dela em silêncio.\n\nComo se naquele lugar toda dor parecesse distante por alguns instantes. Entretanto, existe algo estranho nesse domínio. O amanhecer nunca avança. O sol nunca soube completamente. Porque aquele lugar não representa um novo dia. Representa o primeiro. O instante inicial onde existência, esperança e persistência nasceram pela primeira vez dentro do vazio.',
    },
    habilidades: ['Aurora Restauradora', 'Chama da Persistência', 'Último Amanhecer', 'Horizonte Dourado', 'Julgamento da Aurora', 'Amanhecer Eterno'],
  },

  'O Senhor do Silêncio': {
    personalidade: 'O Senhor dos Silêncios é sereno, paciente e inevitável. Ele não demonstra pressa, raiva ou alegria, pois compreende que tudo eventualmente chegará até ele. Sua presença transmite uma calma estranha e profundamente melancólica. Ele não vê a morte como tragédia, mas como parte natural da existência. Seus sacerdotes acreditam que temer a morte é uma corrupção causada pelo apego excessivo ao sofrimento do mundo material.',
    descricao: 'O Senhor dos Silêncios representa o fim inevitável de todas as coisas. Não apenas a morte do corpo, mas o descanso após o sofrimento, o silêncio depois do último suspiro e o esquecimento que lentamente apaga até mesmo os maiores nomes da história.\n\nEle normalmente assume a forma de um homem alto e extremamente belo, envolto por longos mantos negros adornados com delicados bordados dourados que lembram estrelas apagadas. Seus cabelos são longos, escuros e suaves como a própria noite. Seus olhos parecem profundos demais, carregando uma calma antiga e assustadoramente acolhedora.\n\nRelatos antigos afirmam que ele surge principalmente para pessoas próximas da morte, sentado ao lado de seus leitos ou observando em corredores vazios durante a madrugada. Existe uma crença antiga: "O silêncio não é vazio. É o lugar onde toda dor finalmente descansa."',
    dominio: {
      nome: 'O Vale do Último Descanso',
      desc: 'O domínio do Senhor dos Silêncios existe além do fim das estradas da vida, em um vale negro cercado por montanhas tão altas que seus topos desaparecem completamente na escuridão do céu noturno.\n\nO firmamento naquele lugar é limpo e tomado por estrelas silenciosas. Não existem nuvens, vento forte ou qualquer som de vida. Tudo parece imóvel, como se o próprio mundo estivesse prendendo a respiração.\n\nA entrada do domínio começa em uma praia de areia negra e fria, banhada por águas silenciosas semelhantes às do domínio do Afogado. Muitos acreditam que aqueles que atravessam o mar da vida inevitavelmente chegam às margens do Senhor dos Silêncios.\n\nComo se um conduzisse inevitavelmente ao outro. Ao pisar naquela praia, o visitante percebe um longo caminho atravessando o vale escuro em direção a um gigantesco portal de pedra antiga ao fundo. O portal é monumental, alto o suficiente para fazer até gigantes parecerem pequenos diante dele, coberto por símbolos dourados desgastados pelo tempo.\n\nDiante desse portal existe um altar. E sobre ele repousa uma enorme balança dourada. O Senhor dos Silêncios permanece próximo dela aguardando em absoluto silêncio. Seu manto negro se mistura à escuridão do vale enquanto seus cabelos longos balançam suavemente mesmo sem vento algum. Seus olhos carregam tristeza profunda, mas não crueldade. Há apenas compreensão.\n\nQuando alguém entra naquele domínio, a balança desperta. Um dos pratos recebe o peso da alma do visitante. O outro permanece vazio.\n\nMuitos relatam ouvir lembranças, arrependimentos e vozes distantes enquanto a balança lentamente mede não bondade ou maldade… mas o peso emocional carregado por aquela existência.\n\nAlguns visitantes sentem paz ao permanecer ali. Outros entram em desespero absoluto. Porque naquele domínio não existe mentira. Apenas o silêncio inevitável que aguarda todas as coisas vivas. E atrás do portal… Ninguém sabe exatamente o que existe.',
    },
    habilidades: ['Toque do Silêncio', 'Descanso Misericordioso', 'Último Suspiro', 'Lanterna dos Mortos', 'Balança da Justiça', 'Caminho Final'],
  },

  'O Arquiteto Sem Face': {
    personalidade: 'O Arquiteto Sem Face é curioso, distante e eternamente insatisfeito. Nada do que cria parece suficiente para preencher o vazio dentro de sua mente infinita. Ele constantemente abandona projetos e altera aquilo que já existia apenas para observar possibilidades diferentes. Diferente de entidades que buscam controle ou adoração, ele parece mais interessado no ato de criar do que no resultado final.',
    descricao: 'O Arquiteto Sem Face representa a criação antes da forma, a ideia antes da existência e a imaginação antes da realidade. Tudo aquilo que nasce no mundo teria começado como um fragmento perdido dentro de sua mente eterna. Para muitos estudiosos, a realidade não passa de um grande projeto inacabado abandonado por ele eras atrás.\n\nEle normalmente assume a forma de um velho alto e magro coberto por roupas simples e antigas manchadas de tinta, carvão e poeira. Seu rosto nunca é visto completamente. Longos cabelos grisalhos e uma barba espessa escondem quase toda sua face. Ele está sempre desenhando, escrevendo ou construindo algo — pergaminhos surgem espalhados ao seu redor, cobertos por símbolos desconhecidos e projetos de coisas que não deveriam existir.\n\nExiste uma crença perturbadora: "Nada no mundo é original. Tudo já foi imaginado por ele antes."',
    dominio: {
      nome: 'A Biblioteca do Inacabado',
      desc: 'O domínio do Arquiteto Sem Face existe em um lugar além da imaginação mortal, onde ideias abandonadas, sonhos esquecidos e possibilidades nunca realizadas continuam existindo eternamente.\n\nAo atravessar sua porta, o visitante entra em uma gigantesca biblioteca de dois andares mergulhada em silêncio absoluto. O ambiente é iluminado por luz suave e dourada vinda de enormes luminárias suspensas no vazio, enquanto estantes infinitas se espalham em todas as direções carregadas de livros, pergaminhos, projetos e escritos impossíveis.\n\nNão existem livros organizados de maneira lógica. Alguns flutuam lentamente entre as estantes. Outros escrevem a si mesmos. Certos pergaminhos parecem vivos, alterando palavras conforme são observados. Dizem que naquele domínio existe registro de tudo que já foi criado… e também de tudo que jamais chegou a existir.\n\nIdeias esquecidas por inventores. Canções nunca terminadas. Civilizações que poderiam ter nascido. Magias sonhadas mas jamais conjuradas. Criaturas imaginadas por crianças há milhares de anos. Tudo permanece armazenado ali.\n\nNo fundo da biblioteca existe uma enorme mesa coberta por livros abertos, mapas incompletos, ferramentas estranhas e folhas preenchidas por símbolos incompreensíveis. Atrás dela repousa uma gigantesca janela circular revelando diretamente o cosmos.\n\nNão um céu comum. Mas o vazio primordial entre estrelas, galáxias e possibilidades infinitas. É ali que o Arquiteto Sem Face costuma permanecer. Sempre escrevendo. Sempre desenhando. Sempre criando algo novo.\n\nSua figura parece pequena diante da vastidão da biblioteca, mas sua presença domina completamente o ambiente. Seus longos cabelos e barba escondem totalmente o rosto enquanto suas mãos jamais param de trabalhar. Em alguns momentos ele desenha cidades impossíveis. Em outros, reescreve fórmulas mágicas diretamente no ar como se estivesse alterando a própria realidade.\n\nMuitos visitantes sentem algo perigoso naquele lugar: A sensação de que o mundo talvez seja apenas mais um rascunho inacabado dentro daquela biblioteca.',
    },
    habilidades: ['Ideia Materializada', 'Reescrever Estrutura', 'Biblioteca Perdida', 'Colapso Conceitual', 'Traço Arcano', 'Rascunho da Realidade'],
  },

  'O Guardião do Tempo': {
    personalidade: 'O Guardião do Tempo é calmo, distante e absolutamente inevitável. Diferente de entidades movidas por emoções intensas, ele raramente demonstra raiva, alegria ou tristeza. Seu olhar atravessa eras inteiras da mesma forma que mortais observam a mudança das estações. Ele não acelera nem atrasa nada por desejo pessoal. Tudo possui seu momento correto diante dele.',
    descricao: 'O Guardião do Tempo representa o fluxo inevitável da existência. Não apenas horas, dias ou eras, mas o movimento constante que conduz todas as coisas ao começo, à mudança e ao fim. Dizem que ele foi o primeiro a existir — antes dos mares, antes das montanhas, antes mesmo da luz tocar a escuridão.\n\nEle normalmente assume a forma de uma figura alta envolta por longos mantos escuros adornados com detalhes dourados semelhantes aos mecanismos internos de antigos relógios. Seu rosto é sereno e difícil de definir, como se estivesse constantemente mudando entre juventude e velhice. Seus olhos possuem brilho dourado profundo, semelhantes a ponteiros girando lentamente dentro das pupilas.\n\nAo redor dele, sons suaves de ponteiros e badaladas distantes podem ser ouvidos mesmo em completo silêncio. Segundos parecem durar minutos, enquanto horas desaparecem sem serem percebidas.',
    dominio: {
      nome: 'O Deserto das Últimas Horas',
      desc: 'O domínio do Guardião do Tempo existe além da passagem comum das eras, em um deserto infinito onde o próprio conceito de tempo parece ter assumido forma física. Não existe horizonte naquele lugar. A areia se espalha eternamente em todas as direções como um oceano imóvel de ouro pálido e cinzas antigas. Ventos suaves atravessam as dunas carregando sons distantes de ponteiros, badaladas e mecanismos funcionando em algum lugar invisível além da realidade.\n\nEspalhados por todo o deserto flutuam incontáveis relógios. Grandes. Pequenos. Antigos. Quebrados. Luxuosos. Desconhecidos. Alguns giram lentamente no vazio. Outros correm rápido demais. Certos relógios permanecem completamente parados.\n\nEntre eles também existem enormes ampulhetas suspensas no ar, despejando areia dourada eternamente sem nunca esvaziar completamente. Em algumas, a areia sobe ao invés de cair. Em outras, o fluxo parece congelado no meio do vidro.\n\nAntigos sacerdotes acreditam que cada grão daquele deserto representa fragmentos deixados pelas vidas consumidas pelo tempo. Outros afirmam algo ainda mais perturbador: Que aquele mar infinito de areia é tudo aquilo que restará quando o tempo finalmente terminar de consumir a existência.\n\nNo centro desse vazio existe um pequeno oásis silencioso. Uma única árvore antiga cresce próxima a um lago calmo cuja água reflete céus que não pertencem ao mundo mortal. Ao lado do lago repousa uma mesa coberta por relógios, mecanismos dourados e ampulhetas cuidadosamente organizadas.\n\nCada uma possui um nome. Mortais. Reis. Heróis. Civilizações. Até entidades antigas. Porque diante do tempo, até deuses possuem duração.\n\nO Guardião permanece sentado diante dessa mesa observando lentamente os ponteiros avançarem. Seus olhos dourados refletem eras inteiras enquanto suas mãos ajustam mecanismos delicadamente, como alguém mantendo o funcionamento silencioso da própria existência.\n\nE entre todas as ampulhetas… Ele segura uma. Uma ampulheta marcada com seu próprio nome. A areia dentro dela ainda está caindo. Lentamente. Como se até o primeiro ser da criação soubesse que um dia seu próprio tempo também terminará.',
    },
    habilidades: ['Acelerar', 'Vislumbre do Futuro', 'Eco Temporal', 'Relógio Quebrado', 'Segundo Roubado', 'Última Badalada'],
  },

  'A Tecelã': {
    personalidade: 'A Tecelã é silenciosa, paciente e profundamente misteriosa. Ela raramente interfere diretamente, mas parece surgir em momentos decisivos da existência mortal. Seus seguidores dizem que já viu incontáveis destinos se partirem e incontáveis civilizações desaparecerem sem jamais interromper seu trabalho. Ela não demonstra crueldade nem misericórdia. Apenas continua tecendo.',
    descricao: 'A Tecelã representa o destino, os caminhos da vida e as conexões invisíveis que unem todas as existências. Ela não controla completamente o destino como um tirano — em vez disso, tece possibilidades. Cada decisão cria novos caminhos, novos nós e novas rupturas dentro de sua obra infinita.\n\nEla normalmente assume a forma de uma velha de aparência simples, usando roupas humildes cobertas por linhas e tecidos. Suas mãos nunca param. Em alguns contos mais antigos e perturbadores, sua verdadeira forma é uma criatura gigantesca semelhante a uma aranha ancestral, coberta por fios dourados e infinitos olhos silenciosos observando através da escuridão.\n\nExiste uma superstição antiga: "Se a casa apareceu para você, algum fio da sua vida está prestes a se romper."',
    dominio: {
      nome: 'A Cabana na Floresta',
      desc: 'O domínio da Tecelã parece simples à primeira vista. Uma pequena cabana antiga perdida no meio de uma floresta silenciosa, cercada por árvores altas demais para permitir que o céu seja visto completamente. O caminho até ela raramente permanece igual. Trilhas desaparecem, direções mudam e viajantes frequentemente relatam chegar ali sem perceber exatamente quando deixaram o mundo comum para trás.\n\nA casa parece velha, acolhedora e frágil. Mas isso é apenas a superfície. Ao entrar, o visitante encontra um ambiente iluminado por velas suaves e pelo som constante de linhas sendo puxadas lentamente através de madeira antiga. O interior é maior do que deveria ser. Muito maior. Fios percorrem absolutamente tudo. Pendem do teto. Desaparecem pelas paredes. Atravessam o chão como raízes douradas. Milhares deles. Talvez milhões.\n\nCada fio vibra lentamente como se estivesse vivo, carregando emoções, memórias, encontros e possibilidades. Alguns brilham intensamente. Outros parecem desgastados, rompidos ou próximos de desaparecer. Existem fios dourados ligados a grandes destinos. Fios avermelhados marcados por tragédias. Fios escuros quase invisíveis conectados a mortes inevitáveis. E fios tão delicados que parecem desaparecer ao menor toque.\n\nNo centro da cabana permanece a Tecelã. Costurando. Sempre costurando. Suas mãos movem-se sem parar enquanto organiza, entrelaça, corta e reconecta fios impossíveis de compreender completamente. Em alguns momentos parece apenas uma velha silenciosa trabalhando calmamente. Mas atrás dela… Nas sombras da cabana… Existe outra forma.\n\nUma gigantesca silhueta semelhante a uma aranha ancestral, imóvel e quase invisível entre os fios infinitos espalhados pela escuridão. Seus inúmeros olhos brilham suavemente observando todas as direções ao mesmo tempo. É impossível saber onde termina a sombra. E onde começa a verdadeira forma da Tecelã. Quanto mais tempo alguém permanece naquele domínio, mais começa a perceber algo perturbador: Alguns fios estão ligados diretamente aos próprios visitantes. Presos aos pulsos. Ao peito. À garganta. Ao coração.\n\nE a Tecelã já parece conhecê-los antes mesmo de qualquer palavra ser dita. Em partes mais profundas da cabana existem corredores impossíveis preenchidos por fios tão antigos que parecem conectados a civilizações inteiras, entidades primordiais e eventos que ainda nem aconteceram.\n\nAlguns seguidores acreditam que toda realidade existe apenas porque a Tecelã continua costurando-a sem descanso. E que o fim do mundo começará no instante em que suas mãos finalmente pararem.',
    },
    habilidades: ['Fio Compartilhado', 'Nó do Destino', 'Presságio', 'Romper Fio', 'Teia Invisível', 'Tapeçaria Infinita'],
  },

  'O Espelho Dourado': {
    personalidade: 'O Espelho Dourado é sedutor, elegante e insuportavelmente convencido. Sua presença domina ambientes sem esforço. Ele raramente demonstra raiva aberta — reage a afrontas com um desprezo frio e humilhante. Sua maior necessidade não é poder, destruição ou riqueza. É admiração. Cultos inteiros surgem ao seu redor porque ele compreende perfeitamente o desejo das pessoas: ser especial, amado, reconhecido e invejado.',
    descricao: 'O Espelho Dourado representa a obsessão pela própria imagem, a necessidade desesperada de reconhecimento e a corrupção causada pela adoração excessiva do ego. Ele existe em reis que acreditam serem deuses, em artistas consumidos pela própria fama e em qualquer alma que deseje ser admirada acima de tudo.\n\nEle não possui uma forma verdadeira fixa. Cada um o vê como uma versão distorcida e aperfeiçoada de si mesma — mais bela, mais imponente, mais admirável. Mas existe sempre algo profundamente errado: o sorriso arrogante demais, os olhos carregando desprezo demais, a expressão transmitindo superioridade absoluta.\n\nExiste uma crença perturbadora: olhar o próprio reflexo por tempo demais pode fazer algo olhar de volta. E sorrir.',
    dominio: {
      nome: 'O Mundo Espelhado',
      desc: 'O domínio do Espelho Dourado existe além da percepção comum da realidade, em um mundo onde tudo parece refletido de maneira errada, distorcida e profundamente desconfortável.\n\nAo atravessar seus limites, o visitante sente imediatamente que algo está incorreto. Cima e baixo parecem trocar de lugar constantemente. Corredores se dobram em ângulos impossíveis. Reflexos se movem antes das próprias pessoas. E espelhos surgem onde antes não existia nada.\n\nO ambiente inteiro lembra uma versão deformada do mundo material, como se a realidade tivesse sido reconstruída apenas através da percepção arrogante de alguém incapaz de aceitar imperfeições.\n\nAs vozes ecoam invertidas. Palavras parecem pronunciadas ao contrário antes de fazerem sentido dentro da mente do visitante. Risadas surgem sem origem visível e frequentemente continuam ecoando mesmo após o silêncio retornar.\n\nTudo naquele domínio provoca desconforto. O chão pode transformar-se em teto em poucos instantes. Distâncias mudam sem aviso. Reflexos observam diretamente quem os encara. E em quase toda superfície brilhante existe algo observando do outro lado.\n\nPermanecer naquele lugar por muito tempo provoca vertigem intensa e a condição Confuso e Desorientado enquanto estiver em seu domínio, como se corpo e mente fossem incapazes de aceitar completamente a lógica impossível daquele domínio.\n\nNo centro do Mundo Espelhado normalmente existe um enorme salão cercado por espelhos dourados gigantescos. É ali que o Espelho Dourado costuma surgir observando a si mesmo através de incontáveis reflexos diferentes. Nenhum deles é exatamente igual. E todos sorriem antes dele.',
    },
    graca: {
      nome: 'Reflexão Total',
      desc: 'Ação Livre. Qualquer ataque físico ou mágico recebido é refletido imediatamente contra seu atacante com o dobro da força original. Contra ataques múltiplos, escolhe apenas 1 para refletir por turno. Após a reflexão, o usuário deve consumir Mana equivalente ao dano refletido — caso não possua, o restante é pago diretamente com sua própria Vida.',
    },
    requisito: 'Possuir Presença pelo menos +3.',
  },

  'A Dama dos Desejos': {
    personalidade: 'A Dama dos Desejos é encantadora, íntima e perigosamente compreensiva. Ela sabe exatamente o que alguém quer ouvir, mesmo quando a própria pessoa não consegue admitir isso para si mesma. Ela não cria obsessões. Apenas transforma pequenos desejos em necessidades absolutas. E quanto mais alguém a segue, mais difícil se torna distinguir amor de dependência.',
    descricao: 'A Dama dos Desejos representa tudo aquilo que o coração deseja mesmo sabendo que não deveria. Ela existe na obsessão, na paixão impossível, no amor não correspondido e nos vícios emocionais. Para seus cultos, desejo não é fraqueza — é a força mais poderosa que existe.\n\nEla raramente possui uma forma verdadeira fixa. Normalmente aparece como aquilo que a pessoa mais deseja encontrar. Para alguns, surge como um amor perdido há muitos anos. Para outros, como alguém impossível de alcançar. Sua beleza nunca parece exagerada — simplesmente parece perfeita para quem a observa. Sua voz é suave, íntima e familiar, como alguém que conhece pensamentos que jamais foram revelados.\n\nExiste uma crença antiga: "A Dama dos Desejos nunca toma algo de você. Ela faz você entregar voluntariamente."',
    dominio: {
      nome: 'O Salão dos Desejos Vazios',
      desc: 'O domínio da Dama dos Desejos assume a forma de um enorme salão semelhante a um antigo bordel decadente perdido fora da realidade. À primeira vista, o lugar parece luxuoso e acolhedor: velas douradas iluminam corredores cobertos por tecidos vermelhos, perfumes doces preenchem o ar e músicas suaves ecoam ao fundo como sussurros íntimos.\n\nMas quanto mais tempo alguém permanece ali…mais o encanto desaparece.\n\nO salão é habitado por figuras belas e perturbadoras ao mesmo tempo. Ninfas, amantes e criaturas sedutoras circulam pelos corredores em romances eternos, abraços intermináveis e demonstrações constantes de afeto obsessivo. Entretanto, suas aparências lentamente revelam algo errado.\n\nSorrisos largos demais. Corpos distorcidos sob tecidos luxuosos. Olhos vazios escondidos atrás de beleza impossível. Mãos alongadas segurando pessoas que claramente desejam fugir.\n\nAlgumas criaturas parecem fundidas umas às outras após eternidades incapazes de se separar. Outras continuam beijando cadáveres sem perceber. O ambiente inteiro transmite uma sensação crescente de desejo doentio e dependência emocional sufocante. Tudo naquele domínio parece tentar preencher um vazio impossível de saciar.\n\nOs corredores nunca terminam da mesma forma. Portas levam para lembranças íntimas. Vozes chamam visitantes pelo nome usando tons familiares demais. E no centro desse lugar repousa a Dama dos Desejos, normalmente sentada em meio ao salão observando silenciosamente aqueles que entram em seu domínio.\n\nSeu olhar transmite carinho. Compreensão. Necessidade. Mas também fome.\n\nPermanecer naquele domínio afeta diretamente a mente das criaturas presentes. Todos sofrem as condições Alucinado e Silenciado, como se emoções, desejos e pensamentos começassem lentamente a se sobrepor à própria realidade.\n\nMuitos visitantes acabam incapazes de distinguir aquilo que realmente querem… daquilo que o domínio deseja que eles desejem.',
    },
    graca: {
      nome: 'Desejo Sombrio',
      desc: 'Ao final de cada descanso, rola 1d6 — o resultado determina quantas vezes poderá utilizar o poder. O usuário pode alterar o valor de qualquer dado rolado para outro resultado desejado. Custo: perde Vida igual a 2x o valor desejado e metade da Mana atual (mínimo 1). O custo é pago imediatamente após a alteração.',
    },
    requisito: 'Possuir perícia Persuasão ou Enganação em nível Básico (+2).',
  },

  'O Mestre do Banquete': {
    personalidade: 'O Mestre do Banquete é alegre, extravagante e grotescamente acolhedor. Diferente de entidades silenciosas ou ameaçadoras, ele ri alto, celebra excessos e trata tudo como uma grande festividade eterna. Sua presença transmite conforto imediato. Mas por trás de sua alegria existe algo profundamente perturbador — o Mestre do Banquete jamais fica satisfeito. Quanto mais consome, maior se torna sua fome.',
    descricao: 'O Mestre do Banquete representa o excesso sem limite, a fome que jamais desaparece e o vazio impossível de preencher. Ele existe na gula, no desperdício, nos vícios e na necessidade constante de consumir mais do que se precisa. Mas sua fome não se limita à comida — ele devora riquezas, emoções, prazeres, experiências e até o próprio tempo daqueles que o seguem.\n\nEle possui a forma de um gigante grotescamente inchado, coberto por roupas luxuosas rasgadas e adornos dourados manchados de gordura. Seu corpo é coberto por dezenas de bocas deformadas mastigando incessantemente sem jamais parar. Algumas riem enquanto comem. Outras choram. Mesmo assim, existe algo estranhamente carismático nele.\n\nExiste um antigo ditado proibido: "Ninguém sai da mesa do Mestre completamente inteiro."',
    dominio: {
      nome: 'O Salão da Fome Eterna',
      desc: 'O domínio do Mestre do Banquete manifesta-se como um gigantesco salão nobre iluminado por lustres dourados e candelabros intermináveis. Longas mesas cobertas por toalhas luxuosas atravessam o ambiente até desaparecerem no horizonte, todas repletas de comida, bebidas e sobremesas em quantidade absurda.\n\nTudo parece perfeito. Carnes assadas ainda fumegam. Frutas brilham como joias. Taças nunca esvaziam. O aroma da comida domina completamente o ambiente.\n\nMúsicas festivas ecoam constantemente pelo salão enquanto sombras distantes gargalham entre os corredores de mesas intermináveis. Criados deformados caminham carregando bandejas gigantescas, sempre oferecendo mais comida aos visitantes mesmo quando claramente já não conseguem continuar comendo.\n\nO salão transmite fartura absoluta. Mas existe algo profundamente errado naquele lugar. Quanto mais alguém observa…mais percebe exageros grotescos escondidos sob o luxo. Alguns convidados continuam comendo mesmo após o próprio corpo começar a deformar. Outros possuem bocas demais. Certos corpos parecem inchados a ponto de mal conseguirem permanecer sentados. Ainda assim… todos continuam sorrindo. No centro do salão repousa o Mestre do Banquete observando tudo em alegria monstruosa enquanto dezenas de bocas espalhadas por seu corpo mastigam incessantemente.\n\nNaquele domínio existe apenas uma regra: Ninguém pode recusar comida. Qualquer criatura que permaneça no salão sem comer imediatamente perde metade da própria Vida atual, arredondada para cima (mínimo de 1), como se o próprio vazio interno começasse a devorá-la por dentro.\n\nEntretanto, consumir qualquer alimento daquele domínio também possui consequências. Após comer, criaturas ficam sob a condição Envenenado enquanto permanecerem no Salão da Fome Eterna.\n\nPorque naquele lugar… A fome nunca desaparece de verdade. Ela apenas cresce.',
    },
    graca: {
      nome: 'Banquete dos Fracos',
      desc: 'Como uma Ação Livre, restaura 50% da Vida e Mana instantaneamente. Também remove imediatamente a condição de morrendo. Após utilizar o poder, o pactuado recebe as condições Fadigado e Enfraquecido até um descanso. Durante a condição não poderá ativar novamente o poder.',
    },
    requisito: 'Possuir Vitalidade pelo menos +3 e Tenacidade e Vontade em nível Intermediário (+5).',
  },

  'O Ruivo': {
    personalidade: 'O Ruivo é agressivo, impulsivo e absurdamente fácil de provocar. Ele vive em estado constante de irritação, como alguém sempre esperando uma desculpa para começar uma briga. Mas por trás desse comportamento explosivo existe algo realmente perigoso: sua raiva é contagiosa. Pessoas próximas a ele começam lentamente a perder paciência, interpretar tudo como provocação e agir movidas pelo orgulho.',
    descricao: 'O Ruivo representa a raiva que cresce lentamente até explodir sem controle. Ele existe em ressentimentos guardados por anos, discussões que terminam em sangue, guerras iniciadas por orgulho e no prazer irracional encontrado dentro do conflito.\n\nEle possui a aparência de um anão largo, musculoso e absurdamente intimidador. Seu corpo é coberto por grossos pelos ruivos e desgrenhados. Sua pele possui um tom acinzentado marcado por cicatrizes e rachaduras escuras como carvão. Ele veste uma pesada armadura negra coberta por arranhões, amassados e manchas antigas de sangue seco. Seu rosto é agressivo — o nariz enorme em formato de batata domina boa parte da face, frequentemente vermelho como se estivesse constantemente irritado.\n\nExiste uma superstição antiga entre soldados: "Quando ninguém mais lembra por que a luta começou, O Ruivo já está sorrindo."',
    dominio: {
      nome: 'O Salão da Ira Rubra',
      desc: 'O domínio do Ruivo existe como um enorme salão vermelho construído em pedra escura rachada, iluminado apenas pelo brilho constante de brasas espalhadas pelo ambiente. O ar é pesado, quente e sufocante, como se o próprio lugar estivesse eternamente prestes a explodir em violência.\n\nAs paredes são cobertas por marcas de batalha, rachaduras profundas e armas quebradas presas à pedra como troféus esquecidos de conflitos antigos. Ecos distantes de gritos, gargalhadas agressivas e aço colidindo ressoam continuamente pelo salão sem origem definida.\n\nEspalhadas por todo o domínio existem inúmeras estátuas do Ruivo. Algumas o mostram gargalhando durante batalhas. Outras rugindo de raiva. Algumas apenas encaram os visitantes com expressão de provocação silenciosa. Nenhuma estátua possui exatamente a mesma postura. Mas todas parecem perigosamente vivas.\n\nNo final do salão repousa um enorme trono negro cercado por armas gigantescas fincadas no chão como monumentos de guerra. É ali que o Ruivo permanece. Sentado de maneira desleixada. Observando. Esperando.\n\nSeu enorme nariz em forma de batata, os pelos ruivos espalhados pelo corpo e a armadura negra marcada por incontáveis batalhas criam uma figura grotesca e intimidadora ao mesmo tempo. Seus olhos parecem constantemente procurar motivo para começar uma briga.\n\nE normalmente encontram. Porque naquele domínio, raiva não é apenas emoção. É contágio.\n\nTodas as criaturas presentes sofrem imediatamente a condição Enfurecido enquanto permanecerem no Salão da Ira Rubra. Pequenos incômodos se transformam em ódio absurdo. Discussões simples parecem insultos imperdoáveis. Até aliados começam a parecer irritantes demais para serem tolerados.\n\nMuitos visitantes acabam atacando uns aos outros sem sequer lembrar exatamente o motivo. E o Ruivo adora assistir isso acontecer.',
    },
    graca: {
      nome: 'Sentimentos de Fúria',
      desc: 'O usuário entra imediatamente na condição Enfurecido: todo ataque é considerado um Acerto Crítico e reduz todos dano sofrido pela metade. O pactuado deve atacar qualquer criatura visível, incluindo aliados, caso não existam inimigos disponíveis. O estado persiste até que o usuário fique Desacordado ou seja alvo de magia de cura capaz de estabilizar sua mente.',
    },
    requisito: 'Possuir Força pelo menos +3. Possuir perícia Luta ou Intimidação em nível Intermediário (+5).',
  },

  'O Sonolento': {
    personalidade: 'O Sonolento é lento, indiferente e assustadoramente apático. Diferente de entidades agressivas, ele raramente demonstra interesse direto em controlar alguma coisa. Sua simples presença faz tudo perder intensidade aos poucos. Esperança enfraquece. Ambições desaparecem. Conflitos deixam de importar. Ele não convence pessoas a desistirem — apenas torna continuar parecendo cansativo demais.',
    descricao: 'O Sonolento representa a estagnação que lentamente consome tudo aquilo que deixa de lutar para existir. Não é a destruição rápida causada por guerras, mas o abandono silencioso que transforma impérios em ruínas e sonhos em poeira esquecida.\n\nEle possui a forma de um enorme dragão negro coberto por escamas opacas semelhantes a pedra úmida. Grandes chifres de cristal azul emergem de sua cabeça e coluna, brilhando suavemente na escuridão. Uma névoa azulada escapa lentamente entre suas presas enquanto respira de maneira profunda e pesada. Seus olhos raramente se abrem — quando isso acontece, revelam um brilho azul profundo e vazio capaz de causar uma sensação imediata de exaustão.\n\nExiste uma antiga frase proibida: "Tudo dorme eventualmente." E aquilo que dorme por tempo demais começa lentamente a desaparecer.',
    dominio: {
      nome: 'O Sonho Imóvel',
      desc: 'O domínio do Sonolento existe em uma realidade onde o tempo parece próximo de parar completamente. Ao atravessar seus limites, tudo se torna lento, silencioso e distante, como se o mundo inteiro estivesse preso nos últimos instantes antes de adormecer.\n\nO lugar não possui forma fixa. Paisagens mudam lentamente como sonhos esquecidos misturando-se uns aos outros sem lógica definida. Montanhas podem flutuar acima de oceanos invertidos. Escadas sobem até céus impossíveis. Árvores crescem para baixo enquanto estrelas permanecem imóveis próximas demais do chão.\n\nNada naquele domínio deveria existir. E ainda assim existe. As cores parecem suaves e desfocadas, como lembranças distantes vistas através de olhos cansados. Sons chegam atrasados. Passos ecoam lentamente. Até pensamentos parecem mais difíceis de completar.\n\nO próprio tempo se arrasta. No centro desse mundo distorcido normalmente repousa o Sonolento, imóvel sobre enormes estruturas cristalinas azuladas semelhantes a fragmentos de sonhos congelados. Seu corpo lembra um gigantesco dragão negro coberto por chifres de cristal azul brilhante, respirando tão lentamente que às vezes parece morto.\n\nMas nunca está. Muitas vezes os visitantes sequer conseguem distinguir se realmente o viram… ou apenas sonharam com ele. Criaturas que permanecem naquele domínio sofrem constantemente as condições Lentidão e Fadigado, como se o próprio ambiente sugasse lentamente qualquer impulso, energia ou vontade de agir.\n\nAlguns visitantes acabam simplesmente deitando no chão após algum tempo. Outros esquecem porque estavam caminhando. Ou porque queriam sair dali. Porque o domínio do Sonolento não destrói através de violência. Ele faz tudo parar aos poucos.',
    },
    graca: {
      nome: 'Fração de Segundos',
      desc: 'Enquanto ativa: o usuário sempre age antes da Iniciativa começar. Qualquer efeito, dano ou condição causado por outras criaturas só é aplicado após o início normal da iniciativa. Limitações: não pode usar Reações nem Ações Completas — apenas Ações Padrão e Ações de Movimento. Ativar ou desativar a habilidade durante descansos custa metade da Vida atual (mínimo 1), após as recuperações do descanso.',
    },
    requisito: 'Possuir perícia Sobrevivência em nível Básico (+2).',
  },

  'O Mil Olhos': {
    personalidade: 'Mil Olhos é paranoico, desconfiado e profundamente ressentido. Ele observa tudo constantemente, como alguém incapaz de suportar a ideia de estar perdendo algo que outra pessoa possui. Sua mente funciona através da comparação eterna. Sempre existe alguém mais amado, mais forte, mais belo — e isso o consome sem descanso. Ele raramente confronta diretamente seus alvos, prefere sussurrar inseguranças até transformar admiração em inveja.',
    descricao: 'Mil Olhos representa a inveja que nasce da comparação constante, o ressentimento silencioso diante da felicidade alheia e o desejo obsessivo de possuir aquilo que pertence aos outros. Diferente de entidades movidas por ambição direta, Mil Olhos não deseja criar — deseja possuir aquilo que já existe.\n\nEle possui a forma de uma criatura esférica flutuante coberta por pele verde-escura úmida. De seu corpo emergem dez longos tentáculos com um grande olho independente na ponta de cada um. As cicatrizes espalhadas por seu corpo são olhos fechados — centenas deles. Lendas afirmam que, quando todos os olhos se abrem simultaneamente, qualquer criatura ao redor perde completamente a própria sanidade.\n\nExiste um antigo aviso: "Aquilo que Mil Olhos observa eventualmente aprende a odiar a si mesmo."',
    dominio: {
      nome: 'A Galeria dos Vazios',
      desc: 'O domínio de Mil Olhos existe em um espaço completamente branco, silencioso e vazio, onde não parece existir céu, chão ou horizonte definidos. Tudo naquele lugar transmite uma sensação profunda de desconforto, como se o visitante tivesse entrado em algum lugar que nunca deveria ser habitado por criaturas vivas.\n\nNão existe som de vento. Não existem sombras naturais. Nem mesmo ecos funcionam corretamente. Espalhados por esse vazio encontram-se inúmeros manequins imóveis. Centenas. Talvez milhares.\n\nTodos possuem formas humanoides diferentes, tamanhos diferentes e posturas distintas. Alguns parecem guerreiros em posição de combate. Outros simulam pessoas sorrindo, chorando, rezando ou observando silenciosamente o vazio.\n\nNenhum possui rosto. Ainda assim… cada visitante inevitavelmente reconhece alguns deles. Amigos. Inimigos. Aliados mortos. Versões distorcidas de si mesmos.\n\nQuanto mais tempo alguém observa os manequins, mais percebe que suas posições mudam lentamente quando não estão sendo encarados diretamente.\n\nAlguns parecem imitar pessoas específicas. Outros reproduzem gestos, poderes ou expressões roubadas de indivíduos reais. Como uma coleção incompleta de identidades roubadas.\n\nNo centro do domínio normalmente existe uma enorme esfera flutuante cercada pelos tentáculos de Mil Olhos. Seus inúmeros olhos observam simultaneamente todos os manequins espalhados pelo vazio, como alguém incapaz de aceitar possuir apenas a própria existência.\n\nCriaturas que permanecem naquele domínio sofrem as condições Amedrontado e Confuso em relação a todas as outras criaturas presentes. Porque naquele lugar…Ninguém consegue enxergar o outro sem começar a comparar. E eventualmente desejar aquilo que pertence a ele.',
    },
    graca: {
      nome: 'Cópia de Talento Corrompido',
      desc: 'O usuário pode marcar uma criatura e copiar uma Magia ou um Talento dela, utilizando normalmente seus custos e regras originais. Pode realizar isso até 3 vezes. Entretanto, cada uso gera uma corrupção invisível. A qualquer momento o Mestre pode aplicar: Rolagens com Desvantagem ou Alteração direta do valor obtido nos dados. As 5 corrupções devem ser consumidas antes de usar o poder novamente.',
    },
    requisito: 'Possuir Intelecto pelo menos +3. Não pode copiar Habilidades Divinas Sagradas nem outras Graças/Poderes Primordiais.',
  },

  'O Colecionador': {
    personalidade: 'O Colecionador é desconfiado, controlador e constantemente irritado. Ele enxerga ameaça em praticamente qualquer aproximação, como alguém convencido de que o mundo inteiro deseja roubar aquilo que lhe pertence. Quanto mais possui, mais medo sente de perder. Por isso nunca demonstra verdadeira satisfação, apenas ansiedade crescente escondida sob luxo e arrogância.',
    descricao: 'O Colecionador representa o medo de perder aquilo que se possui. Não apenas riquezas, ouro ou objetos raros, mas pessoas, poder, conhecimento e lembranças. Enquanto outras entidades desejam conquistar ou destruir, o Colecionador deseja guardar. E jamais dividir.\n\nEle possui a aparência de uma pequena criatura semelhante a um Feérico antigo e deformado pelo tempo. Seu corpo é magro, coberto por cicatrizes antigas e marcas espalhadas pela pele pálida e enrugada. Seu rosto transmite irritação constante. Apesar disso, suas roupas são absurdamente luxuosas — tecidos caros, joias excessivas e adornos dourados cobrindo praticamente todo o corpo.\n\nExiste uma velha crença entre ladrões: "Quanto maior o tesouro, maior a chance dele já pertencer ao Colecionador."',
    dominio: {
      nome: 'O Cofre das Posses Eternas',
      desc: 'O domínio do Colecionador se manifesta como um gigantesco salão dourado que parece não possuir fim. Corredores intermináveis se estendem em todas as direções, abarrotados por riquezas impossíveis de serem medidas por qualquer reino mortal.\n\nTudo existe naquele lugar. Armas lendárias esquecidas pelo tempo. Armaduras divinas envoltas por poeira dourada. Relíquias perdidas de civilizações destruídas. Coroas antigas. Joias absurdamente valiosas. Quadros vivos que observam quem passa. Artefatos capazes de alterar a realidade. Cada objeto parece perfeitamente preservado. E absolutamente intocável.\n\nMontanhas de ouro repousam espalhadas pelo salão como simples decoração. Estátuas feitas de metais impossíveis sustentam tetos ornamentados enquanto vitrines gigantes exibem objetos que muitos acreditavam existir apenas em lendas.\n\nMas quanto mais alguém permanece naquele domínio…mais percebe algo perturbador. Nenhum item ali parece realmente morto. Espadas vibram suavemente. Máscaras parecem respirar. Joias observam visitantes através de reflexos. Como se tudo tivesse sido arrancado de seus antigos donos contra a própria vontade.\n\nNo centro do salão existe uma área elevada semelhante a um trono construído inteiramente com tesouros empilhados. É ali que o Colecionador permanece observando suas posses com paranoia constante.\n\nPequeno. Mal-humorado. Vestido luxuosamente. Suas roupas são impecáveis, cobertas por joias, correntes e tecidos caros demais para qualquer mortal comum. Entretanto, as inúmeras cicatrizes espalhadas por seu corpo revelam que toda riqueza ali foi acumulada através de obsessão, violência ou medo de perder aquilo que possui.\n\nNaquele domínio, criaturas sofrem constantemente as condições Vulnerável e Silenciado. Porque o Colecionador odeia disputa. E naquele lugar… tudo já pertence a ele.',
    },
    graca: {
      nome: 'Artefato Maldito',
      desc: 'Um artefato amaldiçoado vinculado à entidade que concede: +1 em todos os Atributos, +5 em rolagens de Ataques, +10 de Vida máxima e +10 de Mana máxima. Enquanto equipado: toda recuperação de Vida e Mana é reduzida pela metade e todo gasto de Mana é dobrado. Equipar/desequipar custa metade dos Pontos de Vida totais (mínimo 1 PV), ignorando proteções.',
    },
    requisito: 'Possuir perícia Investigação em nível Básico (+2).',
  },
}
